### ISSUE TITLE
Another Windows Update casuses the check?

### ISSUE THREAD

**Issue by SomeThrowawayAccount** [zeffy/kb4012218-19#1]
It seems that there's another Windows Update, possibly the April Rollup, that causes the CPU check now too. I don't have kb4012218 or 19, but the CPU checks are present it seems.

If it's not too much trouble, is it possible you can look into this? I'm not sure if there is anything I can do to help.

Thank you for your work!

**Comment by zeffy** [comment]
Sure, I'll look into it! Thanks for letting me know.

**Comment by zeffy** [comment]
Okay, so it looks like KB4012218 and KB4012219 were merged into the April, 2017 Security Monthly Quality Rollup updates KB4015549 and KB4015550 (sneaky!). I'm getting the update files now to see if wuaueng.dll has any new changes, and should be able to have updated patch scripts up some time today or tomorrow.

**Comment by zeffy** [comment]
Just another status update, it looks like there are some changes in wuaueng.dll between the last updates and this security rollup one, so I'll need verify there aren't any new checks etc. before I can push out new patches. Shouldn't take long.

**Comment by perhof** [comment]
Updated versions of wuaueng.dll are included in the security only rollups KB4015546 resp KB4015547 too.
KB4015546 contains the same version as KB4015549
KB4015547 contains the same version as KB4015550

**Comment by zeffy** [comment]
Interesting, thanks for the heads up! I'll include support for KB4015546 and KB4015547 with the new patch.

Quite sneaky of them including these changes in "so-called" security updates. Makes me wonder what other garbage is getting crammed into these rollups...

**Comment by perhof** [comment]
Yes, it certainly makes me wonder too when they stuff things like this into a security update.
I understand that non-security updates to the update engine needs to be included if the update would fail to install without it but this update to the update engine works in the opposite way. It's only there to deliberately make updates fail.

**Comment by zeffy** [comment]
New update has been released which should solve this issue. https://github.com/zeffy/kb4012218-19/releases
