### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ypid** [zeffy/kb4012218-19#10]
Nice work :smirk:

Have you decided yet under which license you want to put your work? May I suggest [GPL-3.0](https://www.gnu.org/licenses/gpl-3.0.html) :wink:

**Comment by zeffy** [comment]
I've been meaning to add one. I think GPL-3.0 would be a good fit for this project, yes. I will add it to the repo.

**Comment by zeffy** [comment]
Added in 19b334b

**Comment by ypid** [comment]
Thanks :)
