### ISSUE TITLE
How to use patch

### ISSUE THREAD

**Issue by faymous4** [zeffy/kb4012218-19#11]
Hi!
Thank you for your patch to bypass microsoft blocking windows 7 updates.  We've just got some new computers at work and they have windows 7 pro 64 bit on the new intel processors.  I have run your application files in your download, and then changed the name of the .dll file and replaced the one in system32.  But when I click 'check for updates' I am still getting the unsupported hardware message. Am I doing something wrong?  I am new to this sort of stuff, so would have loved some detail instructions to make sure that I am doing it right.

**Comment by zeffy** [comment]
You don't have to rename any dll files or do anything manually, just download the latest release here https://github.com/zeffy/kb4012218-19/releases and run aio-wuaueng.dll-patch.bat as administrator and it will guide you through the process. The changes should take effect immediately.

**Comment by faymous4** [comment]
I think I just figured that out! I thought I had to run the other application files and copy the patch, but I just did exactly what you said just before I got your email and now just waiting for the computer to restart to see if it worked!


Kind regards,

Fay
________________________________

**Comment by zeffy** [comment]
Glad to hear it! Let me know how it works for you :)

**Comment by faymous4** [comment]
Worked perfectly thank you so much!


The only update that failed to install (not necessarily anything to do with your patch) but just to let you know was KB4015552.


Kind regards,

Fay
________________________________

**Comment by zeffy** [comment]
It's hard to say if KB4015552 is failing was because of the patch, though. Is Windows Update showing any specific error codes?

**Comment by faymous4** [comment]
Yes, was on the attachment I sent you.  But the error code is 8024200F.  It was only an 'optional' update so I am not too worried.


Kind regards,

Fay
________________________________

**Comment by zeffy** [comment]
Ah, thank you. Attachments sent from email must not show up, I guess.

According to Microsoft, that error means

>The file names contained in the update metadata and in the update package are inconsistent.

I'm installing this update on my own PC to see if it succeeds, will report back shortly.

**Comment by zeffy** [comment]
It worked for me, so it's possible the download just failed or something. If you really want that update you can download the msu package from the update catalog here https://www.catalog.update.microsoft.com/search.aspx?q=KB4015552 and see if that works. But as far as I can tell, that error is unrelated to the patch.

**Comment by zeffy** [comment]
Going to go ahead and close this issue for now, but let me know if you keep having issues.

**Comment by faymous4** [comment]
Yes thank you so much for your help.


Kind regards,

Fay
________________________________
