### ISSUE TITLE
Unsupported hardware issue

### ISSUE THREAD

**Issue by dan-bolsun** [zeffy/kb4012218-19#13]
Hey,

Just try to use patcher on freshly installed Windows 7 64bit (Kaby Lake CPU i7 7700K). Patching did nothing and script suggest to create an issue.

I got this updates checked and try to install them. But Windows Update starts to complain about unsupported hardware.

KB2726535
http://support.microsoft.com/kb/2726535

KB2908783
http://support.microsoft.com/kb/2908783

KB3054476
http://support.microsoft.com/kb/3054476

KB3184143
http://support.microsoft.com/kb/3184143

KB2621440
http://go.microsoft.com/fwlink/?LinkId=232664

KB3042553
http://support.microsoft.com/kb/3042553

KB3109560
http://support.microsoft.com/kb/3109560

KB3110329
http://support.microsoft.com/kb/3110329

KB3139914
http://support.microsoft.com/kb/3139914

**Comment by zeffy** [comment]
To be clear, you have not installed those specific updates yet, correct? Can you post a list of updates you have already installed? 

Also what is the version of your wuaueng.dll? It's located in C:\Windows\System32, right click the file and go to Properties. then the Details tab.

**Comment by dan-bolsun** [comment]
To clarify this issue:
- Updates listed in my first post are not installed yet. And I cannot do this due to "Unsupported Hardware" error.
- Here is a picture of currently installed updates (unfortunately I have no success to export information using wmic qfe command due to "No Instance(s) Available." error):
![installed updates](https://cloud.githubusercontent.com/assets/1249849/25303009/92977b2e-2753-11e7-8723-5ffc48f551c1.JPG)
- Version of wuaueng.dll currently installed: 
![version](https://cloud.githubusercontent.com/assets/1249849/25303059/281939da-2754-11e7-8402-c0dcae2464e6.JPG)

**Comment by zeffy** [comment]
I see in your image you have KB4015549 installed, which is supported by the patch. Since you mention that the wmic qfe command doesn't work for you, I believe that is most likely the issue. The script uses that command internally to see what updates you have installed. 

Other than figuring out what is causing the issue with wmic qfe, I don't really see any other way of fixing this besides modifying the script to bypass the update check and hardcoding KB4015549 as INSTALLED_HOTFIX. 

I can do this for you, if you aren't familiar with batch scripting.

**Comment by zeffy** [comment]
After some quick googling, I found this article which may be related to your problem(?) https://blogs.technet.microsoft.com/askperf/2012/06/29/two-minute-drill-win32_quickfixengineering-no-instances-available/

**Comment by dan-bolsun** [comment]
Yes, I tried to follow this article earlier when want to fix wmic qfe ... output. But with no results. I think it's time for me to move on Windows 10. Thank you for help man.

**Comment by zeffy** [comment]
No problem. Sorry you're having this issue, I wish I knew how to help. :cry:

**Comment by zeffy** [comment]
Hey again @dan-bolsun, if you're still interested I released a new patch version called wufuc which doesn't have this issue anymore. The installer will still spit out a warning about not being able to find any supported updates but it will let you continue anyway.  https://github.com/zeffy/wufuc/releases
