### ISSUE TITLE
Error message: xdelta3-3.0.11-x86_64.exe not found

### ISSUE THREAD

**Issue by kwarkgebak** [zeffy/kb4012218-19#18]
Hello,

When I run this script (in admin mode) I get this error:

File "E:\Downloads\kb4012218-19-master\patch_scripts\aio\xdelta3-3.0.11-x86_64.exe" not found!
Make sure you extracted all the files from the release .zip and try again.

Any idea what's going on?

**Comment by zeffy** [comment]
Judging from the file path I'm guessing you cloned the repository instead of downloading it from the [releases page](https://github.com/zeffy/kb4012218-19/releases). Download it from there and try again.

**Comment by zeffy** [comment]
Going to close this, please let me know if you have any other problems.
