### ISSUE TITLE
No Instances available

### ISSUE THREAD

**Issue by HFStuart** [zeffy/kb4012218-19#25]
On Win 7.1 64 bit

Running the batch file gave the above messages. I am still getting the Unsupported Hardware message.

Report attached. Any ideas?

<details>

## Operating System

```
BuildNumber=7601

Caption=Microsoft Windows 7 Home Premium 

MUILanguages={"en-US"}

OSArchitecture=64-bit

OSLanguage=1033

Version=6.1.7601

```

## Processor

```
Description=Intel64 Family 6 Model 158 Stepping 9

Family=206

Manufacturer=GenuineIntel

Name=Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz

NumberOfCores=2

NumberOfLogicalProcessors=4

ProcessorId=BFEBFBFF000906E9

Revision=

```

## Installed Hotfixes

```
```

## wuaueng.dll Properties

```
MD5 hash of file C:\Windows\System32\wuaueng.dll:
f2 4a 34 5c 58 4e c2 ef c4 9f 9f 37 5e bd a2 a5

SHA1 hash of file C:\Windows\System32\wuaueng.dll:
9c 05 69 63 2f 31 4d a9 2b f6 24 30 44 81 0f dc d8 8c 8a de

SHA256 hash of file C:\Windows\System32\wuaueng.dll:
85 fb b2 11 ca 23 20 36 3b 55 03 e0 6a c2 3c 6a 89 00 7d 37 77 d6 96 df 6d 7a db 23 69 96 5e cd

CreationDate=20170505052547.497000+060

FileSize=2651136

InstallDate=20170505052547.497000+060

LastAccessed=20170505052547.497000+060

LastModified=20170322151728.128446+000

Version=7.6.7601.23735

```
</details>

**Comment by zeffy** [comment]
Hey there. I think you may be having the same issue as #13, which I can't fix from my end. Something (not my script) has probably bugged win32_quickfixengineering in your WMI, so my patch is unable to retrieve the list of updates you have installed. You can try [this supposed solution](https://blogs.technet.microsoft.com/askperf/2012/06/29/two-minute-drill-win32_quickfixengineering-no-instances-available/), but the other guy didn't have any luck. 

Alternatively, you can modify the script to bypass the update check and hard code KB4019264 as `INSTALLED_HOTFIX`. If you don't know how to edit batch scripts, I can do this for you.

**Comment by zeffy** [comment]
Okay, so I went ahead and made some changes to the script that will force detection of KB4019264 and bypass the check. [You can download it here](https://gist.github.com/zeffy/192f94b4fc95c95d5137c1106381f5c9/archive/bbab5f806a383ed070298133584ff12ff5a2a89d.zip). 

Extract `aio-wuaueng.dll-patch_force_kb4019264.bat` into the the same folder where the original `aio-wuaueng.dll-patch.bat` is, and run it as admin, and the patch should work. Keep in mind that if wuaueng.dll gets reverted in an update you will have to repeat the process of hard-coding the KB number again.

**Comment by HFStuart** [comment]
That seems to have worked pretty well.

 

I do now have a message saying my copy of windows in non-genuine but it
doesn't appear to have any effect.

 

Many thanks - I owe you at least a beer for that.

 

Stuart

 

  _____

**Comment by zeffy** [comment]
That's... weird. I'm almost completely certain that has nothing to do with my script, though. 

I'm glad I could help!

**Comment by HFStuart** [comment]
Agreed - Very likely due to me doing a ( gradual ) clean install onto a new
SSD while still using the old version. In any case SLMGR to the rescue..

 

Once again thanks.

 

  _____

**Comment by zeffy** [comment]
No problem, happy to help!

**Comment by zeffy** [comment]
Hey again @HFStuart, if you're still interested I released a new patch version called wufuc which doesn't have this issue anymore. The installer will still spit out a warning about not being able to find any supported updates but it will let you continue anyway.  https://github.com/zeffy/wufuc/releases
