### ISSUE TITLE
Unsupported Hardware message after installing  KB4019265

### ISSUE THREAD

**Issue by kluknawa235** [zeffy/kb4012218-19#27]
after installing KB4019265 , getting message of unsupported Hardware.

**Comment by zeffy** [comment]
Thanks, I'll look into this.

**Comment by zeffy** [comment]
It's a new build number 7.6.7601.23775, so this may take a little longer than usual. Should be done within the day, though.

**Comment by zeffy** [comment]
New version released that should fix this (tested in win7 vm with KB4019265 installed) https://github.com/zeffy/kb4012218-19/releases

Please let me know how it works for you.

**Comment by kluknawa235** [comment]
Hello.

Thanks!

This Script works. Windows Update now Working.

My PC is  AMD ryzen 5 1600, 16 GB ddr4

**Comment by zeffy** [comment]
Awesome! Happy to help. Thanks again for reporting this new update. :)
