### ISSUE TITLE
Pretty please can we have unsigned updates.

### ISSUE THREAD

**Issue by forkoz** [zeffy/kb4012218-19#3]
I cut up win10 to remove all the nasty bits I could find. Unfortunately this prevents the install of any cumulative updates due to ERROR_SXS_ASSEMBLY_MISSING.

I remove the updates from the .mum file but then it fails as TRUST_E_NOSIGNATURE.

So as you've patched the CPU check from 7/8, is it possible to patch the signature check on 10? This would also have a side effect of allowing the editing of the cumulative updates and omitting certain parts.

**Comment by zeffy** [comment]
This sounds interesting, I'll see what I can do. Low priority for now though, until I get the April Security Rollup sorted out.

**Comment by levicki** [comment]
@forkoz I don't think that is possible, but you could always install WSUS server and use WSUS Package Publisher to publish your own self-signed updates. You would need to import your certificate to machine trusted root authorities and trusted publishers store though and modifying updates and resigning them would require considerable knowledge of the WU architecture and the process involved.

**Comment by forkoz** [comment]
Why is it not possible to patch DISM to return true on verification instead of dumping that error? Replace dism, install update, return original dism.

I heard what you say is possible with WSUS but if it connects to the internet it will just re-download the updates from MS servers.

I'm downloading the symbols right now and going to try to disassemble it. Its not about breaking the signature itself just skipping the check on my local machine.

**Comment by zeffy** [comment]
Nice find, @forkoz! That information really helps.

**Comment by forkoz** [comment]
Heh, its harder than I thought though. Some of the updates want the source when installed (CBS_E_SOURCE_MISSING) and win10 dll is different. I think I need something like modern softice to trace what happens when the package told to install.

The WSUS way doesn't look good either. WSUS Package Publisher won't take an uncompressed cab, it wants you to re-create all the steps (ie copy file, write file, etc). I can't do that for 6000 - 2 packages on a 10 cumulative update.

**Comment by levicki** [comment]
@forkoz That's why I said it might not be possible.

As for WSUS server and package publisher, you should be able to manually download, modify, re-sign, and publish your own packages to WSUS using package publisher and set the PC to download from your WSUS server after importing your WSUS self-signed certificate. It is a rather complicated setup though.

As for the CBS part in cbsprovider.dll name that is an acronym for Component Based Servicing, it is the core OS feature and tampering with it and stopping signature enforcement might leave you more vulnerable than you would be if you just skipped all the security updates. Do not forget that Win10 by default uses new delivery optimization for downloading updates which works like torrent protocol downloading from peers on your local network and if allowed it can also download from peers on the internet in order to reduce the load on microsoft WU servers. If you were to disable update signature check then your PC theoretically might download malicious update from a 3rd party.

**Comment by forkoz** [comment]
Yep, that's why I'd patch and undo after the update installs. There doesn't look to be an easy way to re-cab/sign a cumulative update. I tried on 7 with my own certificate and it just changes the error to file not found (:0x80070003/:0x80070002). Don't think you need the server itself to manually install the updates or that it would change much.

As for the peer updates and all of that stuff... The reason I have to modify anything is that those components are gone. No telemetry, alljoyn, peer updates, error reporting, etc. Removed from the wim. 

On 7, the pieces of update actually complete. 8.1 doesn't complain either when components are removed, although it may re-install things. 10 is the only stickler.

**Comment by levicki** [comment]
@forkoz

Certificate must be a self-signed root CA (WSUS generates certificate with CN of `WSUS Publishers Self-signed`), it must be SHA256, it must have Code Signing OID (1.3.6.1.5.5.7.3.3) in extended key usage, and it must be placed in Trusted Publishers as well, not only in Trusted Root Authorities. CAB files should be signed with both SHA1 and SHA256 signature.

Finally, a registry key on the client should be set:
`[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate]
"AcceptTrustedPublisherCerts"=dword:00000001`

 That way works for WSUS, not sure for manual installs.

 I tried using image with removed stuff. It inevitably breaks and corrupts component store sooner or later.

**Comment by zeffy** [comment]
So I had a chance to look into this and analyzed cbsprovider.dll. I agree with both of you, that it seems to be far more complicated than a simple patch to remove signature checking. It's probably best to pursue other solutions such as what @levicki is suggesting. 

I've been pretty busy with development of the patch scripts and other research regarding the future direction of this project, so I don't know if I can dedicate much time to this. I'm going to leave this issue open though, so you can continue discussing it, if you want. Good luck!

**Comment by forkoz** [comment]
heh, it was the weekend :)

I'll try making a cert with all of those qualities and see if it installs. Baring that I have to run dism/cbs in a debugger and step through it processing a package. The tools MS gives to sign stuff are a pain.

I think I'm willing to live with the threat of CBS corruption, it hasn't happened to me on 7 or 8 yet. Its funny that 8.1 is just like 10 minus extra cloud nonsense. I think we have like 4 years to figure this out before applications start dropping support.

**Comment by forkoz** [comment]
The only thing in update.cat is a signature of update.mum

It can be remade with a CDF file:

`[CatalogHeader]
Name=update.cat
ResultDir=.\
PublicVersion=0x0000001
EncodingType=0x00010001
CATATTR1=0x10010001:OSAttr:2:6.0
[CatalogFiles]
<hash>update.mum=.\update.mum
`
Then 

`makecat.exe -v whatever.cdf`

So I made a cert:

`makecert.exe -r -pe -ss CertStore -n "CN=WSUS Publishers Self-signed" TestCert.cer -a SHA256 -eku 1.3.6.1.5.5.7.3.3`

And I tried:

`signtool.exe sign /fd SHA1 /s CertStore /n "WSUS Publishers Self-signed" update.cat`

`signtool.exe sign /fd SHA256 /sha1 CERTSha1 /s CertStore /n "WSUS Publishers Self-signed" update.cat`

After adding to trusted publishers and root authorities and setting the reg key.

CBS gives the error: Failed to initialize internal package [HRESULT = 0x800b0110 - CERT_E_WRONG_USAGE]

**Comment by levicki** [comment]
1. Why do you use /sha1 switch for second command? If I remember correctly that is used to specify the SHA1 thumbprint of the certificate used for signing but you are already supplying store and name, not to mention that the thumbprint is hexadecimal hash.
2. Why didn't you also timestamp the catalog? Keep in mind that switches are `/t` for SHA1 and `/tr` as well as `/td SHA256` for SHA256 timestamp.
3. Did you check if you have both signatures after signing or just one? For dual-signing you need to specify `/as` (append signature) on the second command.
4. Can you upload certificate somewhere so I can take a look?

**Comment by forkoz** [comment]
1. I thought it was needed for second signing with sha256. /as is not recognized as an option
2. I did timestamps... although just the /t version and it made no difference
3. It comes back as not verified because its not chained to MS root cert, I think it is only signing in 256. Although original update.cat only looks to be signed with 256.

4. http://www.filedropper.com/testcert

**Comment by levicki** [comment]
If `/as` is not recognized then your version of signtool.exe is old. Get the one from Windows 8.1 SDK.

For SHA256 only you do it like this (put the following in `sign.bat`):
     @echo off
     "%ProgramFiles(x86)%\Windows Kits\8.1\bin\x86\signtool.exe" sign /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 /sha1 2601bf24bf025979f3e7337060a2d2aeaabf0a98 %1

You pass the file to sign to `sign.bat`.

As for chaining to MS certificate, that is needed for driver signing. Should not be needed for WU (it certanly works on my WSUS at work).

**Comment by forkoz** [comment]
I got the w8.1 tools and re-generated certs. Timestamped with digicert and still no dice.

CERT_E_WRONG_USAGE

both cat files look like they are signed the same way now with sha256.
http://www.filedropper.com/catalogs2

Don't know if I will also have to change the contents of the .mum

`<assembly xmlns="urn:schemas-microsoft-com:asm.v3" manifestVersion="1.0" description="Fix for KB4015217" displayName="default" company="Microsoft Corporation" copyright="Microsoft Corporation" supportInformation="http://support.microsoft.com/?kbid=4015217" creationTimeStamp="2017-03-30T00:43:23Z" lastUpdateTimeStamp="2017-03-30T00:43:23Z">
  <assemblyIdentity name="Package_for_RollupFix" version="14393.1066.1.8" language="neutral" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" />`

Looks like signatures but I've only modified the update.mum deleting 2 packages.

**Comment by levicki** [comment]
@forkoz 

No, AFAIK contents don't have signature.

As for Microsoft certificate used to sign this, it has another eku -- `Windows System Component Verification (1.3.6.1.4.1.311.10.3.6)`, and there is also SAN (Subject Alternative Name) entry with:
`Directory Address:
     SERIALNUMBER="229879+147449be-15a8-4eba-93f3-d110a5c45552"
     OU=MOPR
`
Furthermore, it seems that when signing the catalog you should also add:

@"%ProgramFiles(x86)%\Windows Kits\8.1\bin\x86\signtool.exe" sign /d "Microsoft Windows" /du "http://www.microsoft.com/windows" /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 /sha1 2601bf24bf025979f3e7337060a2d2aeaabf0a98 %1

Finally, the catalog itself does not have all the same attributes (check OID 1.3.6.1.4.1.311.12.2.1 inside).

This tells me that signing those files is totally different than signing drivers or update CAB or MSI files. You can try replicating the exact Microsoft structures OIDs, attributes, etc, but I doubt it will ever work.

**Comment by levicki** [comment]
Let me help you out a little bit more in case you decide to continue, the .cdf file should have the following:

    CatalogVersion=2
    HashAlgorithms=SHA256
    CATATTR1=0x10010001:OSAttr:2:5.1,2:5.2,2:6.0,2:6.1,2:6.2,2:6.3,2:10.0

Note that it took me a while to figure out how to specify OSAttr properly to get identical binary encoding because this is not documented anywhere.

**Comment by levicki** [comment]
UPDATE: I managed to create a signed `.cat` file for which my system says is OK.

It is enough to place the certificate into Trusted Root Authorities and the CN can be anything you want.

1. Generate certificate:
`makecert.exe -r -pe -ss CertStore -n "CN=MASTER" MASTER.cer -a SHA256 -eku 1.3.6.1.4.1.311.10.3.6,1.3.6.1.5.5.7.3.3`

2. Import into Trusted Root Certificate store for machine account:
`certmgr.exe -add MASTER.cer -c -s -r localMachine root`

3. Include OSAttr in `.cdf` file as shown above.

4. Sign the catalog:
`"%ProgramFiles(x86)%\Windows Kits\8.1\bin\x86\signtool.exe" sign /s CertStore /d "Microsoft Windows" /du "http://www.microsoft.com/windows" /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 /sha1 0cac1eb2b363d6056a9dc23e06c46f333687a7e1 %1`

**Comment by forkoz** [comment]
I had Sha256 and version 2 before :) Made the cert.

`[CatalogHeader]
Name=update.cat
ResultDir=.\
CatalogVersion=2
HashAlgorithms=SHA256
CATATTR1=0x10010001:OSAttr:2:5.1,2:5.2,2:6.0,2:6.1,2:6.2,2:6.3,2:10.0
[CatalogFiles]
<hash>update.mum=.\update.mum`

Signed it. 
`signtool.exe sign /s CertStore /n "MASTER" /d "Microsoft Windows" /du "http://www.microsoft.com/windows" /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 update.cat`

And now get `Failed to verify if catalog file \\?\C:\Windows\CbsTemp\30589403_786166456\update.cat is valid. [HRESULT = 0x80090352 - Unknown Error]`

http://www.filedropper.com/showdownload.php/update

**Comment by levicki** [comment]
Your download link is broken. As for the error, I don't know. I am testing on Windows 8.1. If you are doing it on Windows 10 maybe there is something else at play.

**Comment by forkoz** [comment]
Try: http://www.filedropper.com/update
