### ISSUE TITLE
Pb utilisation patch

### ISSUE THREAD

**Issue by pompon1** [zeffy/kb4012218-19#30]
Hello,

With Windows 7 64 bits, le patch ne fonctionne pas 

ci-joint le log

Help-me please

Thanks
[aio-wuaueng.dll-patch.bat-debuginfo_2017-05-20_08-20-38_274000.zip](https://github.com/zeffy/kb4012218-19/files/1015964/aio-wuaueng.dll-patch.bat-debuginfo_2017-05-20_08-20-38_274000.zip)

**Comment by zeffy** [comment]
I think this is the same problem as #13 and #25 

[Download this](https://share.riseup.net/#aCiXZzrYJ3jHaeXlwFDB9A) and run `aio-wuaueng.dll-patch_force_KB4019264.bat` as administrator. This should fix your problem.

---

(Google translated)

Je pense que c'est le même problème que #13 et #25

[Téléchargez ceci](https://share.riseup.net/#aCiXZzrYJ3jHaeXlwFDB9A) et exécutez `aio-wuaueng.dll-patch_force_KB4019264.bat` en tant qu'administrateur. Cela devrait résoudre votre problème.

**Comment by pompon1** [comment]
Merci
Le patche a fonctionné : 
Lancement cmd en tant qu'administrateur + aio-wuaueng.dll-patch_force_KB4019264.bat
Ensuite, le lancement de Windows update détecte 4 maj (depuis le 14/04/2017)
Par contre, suite au redémarrage, maj bloquées = pourrais-je utiliser le même patch ?

En tout cas, merci pour tout.

Honteux de la part de Microsoft : je dois rester en SEVEN car j'ai un logiciel professionnel (licence à 9000€ qui n'est pas compatible Windows 10). Donc avec un PC neuf, ça devient compliqué.

Cordialement

**Comment by zeffy** [comment]
You're very welcome! 

Could you run `aio-wuaueng.dll-patch.bat` (the original one that didn't work) and post another debugging info log? I need the version information for `wuaueng.dll` to be sure which patch you need.

---

(Google translated)

Vous êtes les bienvenus!

Pourriez-vous exécuter `aio-wuaueng.dll-patch.bat` (l'original qui n'a pas fonctionné) et publier un autre journal d'info de débogage? J'ai besoin des informations de version pour `wuaueng.dll` pour être sûr de quel patch vous avez besoin.

**Comment by pompon1** [comment]
Hello,
ci-joint, les 2 logs issus des 2 bat



[aio-wuaueng.dll-patch.bat-debuginfo_2017-05-21_07-26-49_717000.txt](https://github.com/zeffy/kb4012218-19/files/1016680/aio-wuaueng.dll-patch.bat-debuginfo_2017-05-21_07-26-49_717000.txt)

**Comment by zeffy** [comment]
Thanks, [download this script](https://share.riseup.net/#nK9bpQA7FvKyHGB7wrNOUA) and it should work for you.

Also, I'm working on a permanent solution to this problem, but I don't know when it will be finished.

---

Merci, [télécharger ce script](https://share.riseup.net/#nK9bpQA7FvKyHGB7wrNOUA) et cela devrait fonctionner pour vous.

De plus, je travaille sur une solution permanente à ce problème, mais je ne sais pas quand il sera terminé.

**Comment by pompon1** [comment]
Hello,
avec le dernier script, ça fonctionne à nouveau

pourriez-vous me signaler quand la solution permanente à ce problème sera terminée pour l'avoir au cas où?

Merci pour tout et bravo pour tout ce travail (l'union fait la force)

**Comment by zeffy** [comment]
Sure, I will comment here again to let you know when I am finished with the permanent solution. :)

You're very welcome, always happy to help. 

---

Bien sûr, je vais commenter ici pour vous faire savoir quand j'ai fini avec la solution permanente. :)

Vous êtes les bienvenus, toujours heureux de vous aider.

**Comment by zeffy** [comment]
Hello again @pompon1, if you're still interested I released a new patch version called "wufuc" which doesn't have this issue anymore. The installer will show a warning about not being able to find any supported updates, but it will let you continue anyway.  https://github.com/zeffy/wufuc/releases

---

Bonjour encore @pompon1, si vous êtes toujours intéressé, j'ai publié une nouvelle version de patch appelée "wufuc" qui n'a plus ce problème. Le programme d'installation affichera un avertissement sur le fait de ne pas pouvoir trouver de mises à jour prises en charge, mais il vous permettra de continuer de toute façon. Https://github.com/zeffy/wufuc/releases
