### ISSUE TITLE
Patch script fails to properly detect administrator rights when run elevated (unrelated `net session` error?)

### ISSUE THREAD

**Issue by logan-19** [zeffy/kb4012218-19#31]
Hello! I select right-click on "Run as administrator", but does not work, I still receive a message "run as administrator".
How install patch?
Thanks!

![1](https://cloud.githubusercontent.com/assets/28824929/26275886/9b81d792-3d84-11e7-9bb2-ec5940ff600f.jpg)

**Comment by zeffy** [comment]
That's very strange, I may have to come up with another way to check privileges. Out of curiosity, what version of Windows 7 do you have (Ultimate/Premium/Home etc)?

You can try [downloading this](https://gist.github.com/zeffy/55eb4a86bbd6352bb8c2e44242db3c0e/archive/b2a26e084d7109c4df8c5a4920306246096740f7.zip) and put `aio-wuaueng.dll-patch_no_admin_check.bat` in the same folder as `aio-wuaueng.dll-patch.bat`. Run the new batch file as admin and it *should* work.

Please let me know how it works or if you need any more help.

**Comment by logan-19** [comment]
Thanks for the quick response!
I have a system Windows 7 SP1 x64 Ultimate

I checked your patch on the VirtualBox (Win7 x32 Ultimate) with the Sandy Bridge processor and on the computer (Win7 x64 Ultimate) with the Kaby Lake processor on both systems I received the message "Run as administrator"

Now downloaded `aio-wuaueng.dll-patch_no_admin_check.bat` and now everything is fine, the Windows update is unlocked. I also select right-click on "Run as administrator" and got a patch installation.
Thank you very much!

**Comment by zeffy** [comment]
Interesting... This seems like it is an edge case, but I will look into it further and try to find a different way to check for admin rights.

No problem, glad I could help. :)

**Comment by zeffy** [comment]
Hey again @logan-19, I released a new patch version called wufuc which I believe should no longer have this issue. If you are still interested, could you check the installer and see if the admin check works correctly? Thanks.  https://github.com/zeffy/wufuc/releases
