### ISSUE TITLE
Generation of assembler and pseudo C code

### ISSUE THREAD

**Issue by jimuk** [zeffy/kb4012218-19#33]
Hi,

Please can I ask which tools you used to generate the assembler and pseudo C listings of the DLL? 

This technique could be really useful in the future (especially the pseudo C which helps understanding).

Jim

**Comment by zeffy** [comment]
Hey there! I used the Hex-Rays decompiler in IDA Pro to generate the pseudo-C for the write-up, however there are also other less costly alternatives, such as Snowman decompiler which is included in [x64dbg](http://x64dbg.com), although the output is not quite as good.
