### ISSUE TITLE
Support systems using non-English localization

### ISSUE THREAD

**Issue by royblack** [zeffy/kb4012218-19#6]
Sadly it doesn't seem to detect the forementioned version correctly, although it's returning a correct version number and bittage.
Has anyone maybe got this working?

**Comment by zeffy** [comment]
Can you confirm that you have one of the [supported updates](https://github.com/zeffy/kb4012218-19/blob/master/docs/Supported_Updates.md) installed? You can check this by opening Windows Update and reviewing your installed updates.

If you do, which one is it?

If not, can you give me a list of any updates you recently installed?

Thanks!

**Comment by RussianBarbarian** [comment]
wmic /output:stdout os get osarchitecture | find "64-bit"
this must be changed with
wmic /output:stdout os get osarchitecture | find "64"
for international suport

**Comment by zeffy** [comment]
Interesting, thank you! I was wondering if it had something to do with localization. Out of curiosity, what does it output on German or other non-English systems?

**Comment by royblack** [comment]
Thanks :-)

It's returning "64-Bit" with a capital "B"

**Comment by RussianBarbarian** [comment]
64-разрядная in Russian

**Comment by zeffy** [comment]
Sweet, thank you both! I'll make sure this gets fixed in the next update. (probably later today or tomorrow)

**Comment by RussianBarbarian** [comment]
in other languages problem may be with
icacls "%WUAUENG_DLL%" /grant Administrators:F
in Russian icacls "%WUAUENG_DLL%" /grant Администраторы:F

**Comment by zeffy** [comment]
Very true, thanks for pointing that out. I'll see what I can do about making the script culture-independent.

**Comment by zeffy** [comment]
Just released new update which should fix both of these issues, please test it if you get a chance! https://github.com/zeffy/kb4012218-19/releases

**Comment by royblack** [comment]
Brilliant, confirmed working on the german version. Good Job!
