### ISSUE TITLE
Intel Atom Z530

### ISSUE THREAD

**Issue by hooddy** [zeffy/kb4012218-19#7]
I've very outdated CPU Intel Atom Z530 which have banned for updates. Your patch willn't fixed it. Which info ya need to add support for my banned CPU?

**Comment by zeffy** [comment]
You get this window when you try to update? Or is it some other error?

<img width=300 src="https://cdn.ghacks.net/wp-content/uploads/2017/04/unsupported-hardware.png"/>

**Comment by hooddy** [comment]
Yes that's it. In the same time WU is working yet.

**Comment by zeffy** [comment]
Huh, that's actually really odd. 

Could you try again with the new release I posted right after you made created this issue? Just to rule out that it was any of the issues I already fixed. Here's a link https://github.com/zeffy/kb4012218-19/releases

If that still doesn't work, could you post the output of the script window here, so I can see where it is failing?

**Comment by hooddy** [comment]
Thanks. Updated version is works well (i suppose). Thanks for your job. What about odd with outdated CPUs i think MS know this shit. I can inly guess is it mistakes or is it targeted.

**Comment by zeffy** [comment]
Glad to hear it is working for you! It is possible Microsoft made a simple mistake, as I've seen other people with older Sky Lake systems from 2015 getting locked out, too. We'll have to wait and see if they remedy it with yet another update, or if they just ignore the problem.

Anyways, closing this issue for now.
