### ISSUE TITLE
Checksum mismatch problem on Windows 7 x64 when patching KB4012218 (possibly others?) due to mislabeled xdelta files

### ISSUE THREAD

**Issue by DavidHi75** [zeffy/kb4012218-19#8]
Hello zeffy, and thank you very much for your work!
I recently upgraded my hardware... and had this sad surprise!!! :(
Unfortunately I've not been able to apply your patch because of this error:

xdelta3: target window checksum mismatch: XD3_INVALID_INPUT
xdelta3: normally this indicates that the source file is incorrect
xdelta3: please verify the source file with sha1sum or equivalent

Below I attach the full console output.
Can this be due to italian version of Windows?
[issue.txt](https://github.com/zeffy/kb4012218-19/files/944921/issue.txt)

**Comment by zeffy** [comment]
Hmm, what is the version of your wuaueng.dll? It's located in C:\Windows\System32, right click the file and go to Properties, then the Details tab. Also if you know how, can you get the SHA-1 hash of wuaueng.dll as well and post it here? Thanks!

Also I don't believe this is because of the Italian version of Windows, it is possible I mixed up one of the patch files, but I need the file version to confirm.

**Comment by DavidHi75** [comment]
wuaueng.dll version is 7.6.7601.23714
and this should be the SHA-1 Hash (obtained on https://onlinemd5.com/):
B7D8F1B4B375561BC4D5EE99E2F69B5FA1BAEF71

Thank you very much ! :)

**Comment by zeffy** [comment]
Okay yeah, that is the same file I have. I definitely must have mixed up a couple of the xdelta files. Really sorry about that! 

I will remake all the patches and release another update later today, but in the meantime I created new xdelta files for KB4012218-x64, which should work for you. Simply drop the new .xdelta files into the `patches` folder and replace the old ones. [You can download them here](https://share.riseup.net/#m-L_GxbBLZcV8kNe8N711A), for some reason github isn't letting me attach the file to this comment.

**Comment by DavidHi75** [comment]
IT WORKED!!! :D 
Thank you very much! ;)

**Comment by zeffy** [comment]
Awesome, very glad I could help! Thank you for reporting this issue. 

I'll close this once I push the new release.

**Comment by zeffy** [comment]
Just released a new hotfix update v0.4a-alpha which should fix this issue. https://github.com/zeffy/kb4012218-19/releases
